### PR TITLE
CLOUDP-163790 Update command "backups schedule update"

### PR DESCRIPTION
**Pull request by fmenezes**
## Proposed changes

Adds filename to backup schedules command

_Jira ticket:_ CLOUDP-163790

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [x] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by wtrocki** [comment]
Changes looks good. Need time to verify (getting cluster)

**Review by gssbzn — APPROVED** [review]
LGTM but, does schedule currently have any e2e? if yes could we add to it? if not do we plan to add some?

**Comment by wtrocki** [comment]
>  if yes could we add to it? if not do we plan to add some?

I assumed that we do not and wanted to start manual tests. Let me know

**Review by wtrocki — APPROVED** [review]
LGTM (reviewed only)

**Review by tibulca — APPROVED** [review]

**Comment by fmenezes** [comment]
@gssbzn schedules currently has no e2e, I'll add it as part of a next PR (created a jira CLOUDP-164740)

**Review by sarahsimpers — COMMENTED** [review]
Hi @fmenezes, copy looks good, but we should probably provide guidance in the docs on what this file should look like. Do we have an e2e test with a working file that docs could use for this? Thanks!

**Comment by sarahsimpers** [comment]
> Hi @fmenezes, copy looks good, but we should probably provide guidance in the docs on what this file should look like. Do we have an e2e test with a working file that docs could use for this? Thanks!

Whoops, just saw in discussion above it's being added later. Thanks!

**Comment by fmenezes** [comment]
> Hi @fmenezes, copy looks good, but we should probably provide guidance in the docs on what this file should look like. Do we have an e2e test with a working file that docs could use for this? Thanks!

@sarahsimpers also check DOCSP-28323

**Pull request merged**
