### PR TITLE
CLOUDP-167771: events commands migration

### PR DESCRIPTION
**Pull request by matt-condon**
## Proposed changes

Migration of Events API to Autogenerated Go SDK 

_Jira ticket:_ CLOUDP-167771
## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by wtrocki** [comment]
:eye:

**Comment by wtrocki** [comment]
Do we have confidence in integration test

**Comment by matt-condon** [comment]
> Do we have confidence in integration test

Decent confidence, since they were failing prior to the fix

**Review by wtrocki — DISMISSED** [review]
Changes LGTM. Verified.
Thanks for bumpin SDK

**Review by wtrocki — COMMENTED** [review]
Reviewed code. Looks good

**Review by wtrocki — DISMISSED** [review]

**Review by swattyT — DISMISSED** [review]
LGTM. Although the e2e passes have the response type in test/e2e/atlas/events_test.go changed?

**Comment by matt-condon** [comment]
> LGTM. Although the e2e passes have the response type in test/e2e/atlas/events_test.go changed?

Ah good spot, the structs were almost identical so it unmarshalled the same
Updated in the latest commit

**Review by wtrocki — APPROVED** [review]

**Pull request merged**
