### PR TITLE
CLOUDP-234267: Update Atlas CLI Docs

### PR DESCRIPTION
**Pull request by danielz117**
## Proposed changes

Updates documentation for Datadog API Region selection to add Japan AP1 region
Related to this ticket: https://jira.mongodb.org/browse/CLOUDP-229909

_Jira ticket:_ [CLOUDP-234267](https://jira.mongodb.org/browse/CLOUDP-234267)

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by jeroenvervaeke — APPROVED** [review]
LGTM

**Comment by gssbzn** [comment]
[Try running: make gen-docs](https://github.com/mongodb/mongodb-atlas-cli/actions/runs/8098597799/job/22132365926?pr=2685)

**Comment by danielz117** [comment]
Generated the docs file and pushed the updated change to the text file

**Review by gssbzn — APPROVED** [review]
LGTM

**Pull request merged**
