### PR TITLE
(DOCSP-31837) Non-copyable code blocks

### PR DESCRIPTION
**Pull request by lmkerbey-mdb**
[JIRA](https://jira.mongodb.org/browse/DOCSP-31837)

### CODE REVIEW

**Review by gssbzn — CHANGES_REQUESTED** [review]
these docs are autogenerated, you need to make the change to https://github.com/mongodb-labs/cobra2snooty

**Comment by gssbzn** [comment]
I think this may be the file https://github.com/mongodb-labs/cobra2snooty/blob/main/examples.go you want to change

**Comment by gssbzn** [comment]
> Try running: make gen-docs

**Review by sarahsimpers — APPROVED** [review]
LGTM, thank you for this change Lander!

**Review by gssbzn — APPROVED** [review]
LGTM

**Pull request merged**
