### PR TITLE
CLOUDP-279533 Add support to load proxy settings from network settings

### PR DESCRIPTION
**Pull request by fmenezes**
## Proposed changes
Add support to load proxy settings from network settings

_Jira ticket:_ CLOUDP-279533

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

## Further comments

this PR gets proxy settings from env on all OSes but on Windows and macOS it goes an extra mile to get settings from os see https://github.com/rapid7/go-get-proxied?tab=readme-ov-file#configuration for more info

### CODE REVIEW

**Comment by jeroenvervaeke** [comment]
Tested on:
- MacOS: Sonoma 14.7.1, working
- Ubuntu 22.04: was already working, but only when restarting the terminal after changing proxy settings (the default ubuntu terminal sets `HTTP_PROXY` and `HTTPS_PROXY`)

**Comment by gssbzn** [comment]
>Tested on:

Any test on windows?

**Comment by fmenezes** [comment]
> Does it work with authenticated proxies? based on this issue seems like a no for at least mac [rapid7/go-get-proxied#15](https://github.com/rapid7/go-get-proxied/issues/15)

No it does not, tested locally

> [IANAL] any concern on this issue [rapid7/go-get-proxied#16](https://github.com/rapid7/go-get-proxied/issues/16)

Legal might be best positioned to answer

**Comment by fmenezes** [comment]
Given the legal concerns plus the library chosen seems unmaintained, I'll close this ticket at the moment, if the presented issues get resolved I'd reconsider this change

**Pull request closed without merging**
