### PR TITLE
CLOUDP-133383: fix repo tests

### PR DESCRIPTION
**Pull request by fmenezes**
## Proposed changes

fix tests to verify pkgs were uploaded to repos

_Jira ticket:_ CLOUDP-133383

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

## Further comments

unfortunately these tests are expected to run during a release so we can only check them during a release

### CODE REVIEW

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Comment by fmenezes** [comment]
evergreen retry

**Comment by fmenezes** [comment]
evergreen retry

**Comment by fmenezes** [comment]
evergreen retry

**Pull request merged**
