### PR TITLE
CLOUDP-112348: Update docs links to include atlascli documentation

### PR DESCRIPTION
**Pull request by andreaangiolillo**
## Proposed changes

_Jira ticket:_ CLOUDP-112348

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongocli/blob/master/CONTRIBUTING.md) (if appropriate)
- [x] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [x] I have updated [e2e/E2E-TESTS.md](https://github.com/mongodb/mongocli/blob/master/e2e/E2E-TESTS.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

## Further comments

We have recently gotten the dochub links for atlascli (these links will work once doc is ready). This PR adds these links to the codebase.

### CODE REVIEW

**Review by sarahsimpers — APPROVED** [review]
LGTM

**Review by gssbzn — APPROVED** [review]
LGTM

**Comment by gssbzn** [comment]
@andreaangiolillo make sure the release manifest looks ok

**Comment by andreaangiolillo** [comment]
Ack. : )


[mongocli.json](https://mongodb-mongocli-build.s3.amazonaws.com/mongocli-master/dist/c7433f29d45068f069e9f21311378f4e87c37ea0_22_03_29_17_16_00/mongocli.json) looks ok

```
 "previous_releases_link": "https://github.com/mongodb/mongodb-atlas-cli/releases",
  "release_date": "2022-03-30T09:39:53.663787Z",
  "release_notes_link": "https://docs.mongodb.com/mongocli/v1.23.1/release-notes/",
  "tutorial_link": "https://www.mongodb.com/docs/mongocli/stable/install/",
  "version": "1.23.1",
  "manual_link": "https://docs.mongodb.com/mongocli/v1.23.1/",
```

[mongodb-atlas-cli.json](https://mongodb-mongocli-build.s3.amazonaws.com/mongocli-master/dist/c7433f29d45068f069e9f21311378f4e87c37ea0_22_03_29_17_16_00/mongodb-atlas-cli.json) looks good 

```
  "previous_releases_link": "https://github.com/mongodb/mongodb-atlas-cli/releases",
  "release_date": "2022-03-30T09:35:04.975383Z",
  "release_notes_link": "https://dochub.mongodb.org/core/atlas-cli-changelog",
  "tutorial_link": "https://dochub.mongodb.org/core/install-atlas-cli",
  "version": "1.0.1",
  "manual_link": "https://dochub.mongodb.org/core/atlas-cli",
```

**Pull request merged**
