### PR TITLE
docs: update RELEASING.md

### PR DESCRIPTION
**Pull request by gssbzn**
Update the RELEASING doc to highlight our internal tooling is now in place

### CODE REVIEW

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Review by colm-quinn — APPROVED** [review]
LGTM (thanks for the cleanup)

**Review by tibulca — APPROVED** [review]

**Review by blva — APPROVED** [review]
LGTM

**Comment by gssbzn** [comment]
evergreen retry

**Comment by gssbzn** [comment]
evergreen retry

**Comment by gssbzn** [comment]
evergreen retry

**Comment by gssbzn** [comment]
evergreen retry

**Pull request merged**
