### PR TITLE
CLOUDP-121183: Ask before opening the browser

### PR DESCRIPTION
**Pull request by blva**
## Proposed changes

_Jira ticket:_ [CLOUDP-121183](https://jira.mongodb.org/browse/CLOUDP-121183)
## Setup
Screenshot 2022-05-12 at 12 17 26

Screenshot 2022-05-12 at 12 17 26

## Register

Screenshot 2022-05-12 at 12 17 39

## Login
Screenshot 2022-05-12 at 12 16 04

Screenshot 2022-05-12 at 12 16 21

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [e2e/E2E-TESTS.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/e2e/E2E-TESTS.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by dianchenghu — COMMENTED** [review]
Can we remove the automatically?  "Open default browser? Y/n "
Other parts look good to me.

**Comment by blva** [comment]
> Can we remove the automatically? "Open default browser? Y/n " Other parts look good to me.

Thank you, I've updated it. Since that was the only change I'll leave the screenshots as is.

**Review by dianchenghu — APPROVED** [review]
LGTM

**Review by sarahsimpers — DISMISSED** [review]
LGTM

**Review by tibulca — DISMISSED** [review]

**Review by tibulca — DISMISSED** [review]

**Review by tibulca — APPROVED** [review]

**Pull request merged**
