### PR TITLE
CLOUDP-226446: Add archives.rlcp=false to the goreleaser files

### PR DESCRIPTION
**Pull request by andreaangiolillo**
## Proposed changes

_Jira ticket:_ CLOUDP-226446

This PR adds `archives.rlcp=false` as its default value has changed in the recent gorelease release. This was preventing us from using the latest [v1.24-pro version](https://github.com/goreleaser/goreleaser-pro/releases/tag/v1.24.0-pro). As part of this PR, I have also upgraded the gorelease evergreen tasks to use the latest gorelease release.

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [x] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

## Further comments

Goreleaser tasks [Packaging MongoCLI (goreleaser)](https://evergreen.mongodb.com/task_log_raw/mongodb_atlas_cli_master_goreleaser_mongocli_snapshot_package_goreleaser_patch_71f6bd2489d0fa6fd567dc692d96da8b681082b8_65c60fb01e2d171458d3cfda_24_02_09_11_42_41/0?type=T#L350) [Packaging AtlasCLI (goreleaser)](https://evergreen.mongodb.com/task/mongodb_atlas_cli_master_goreleaser_atlascli_snapshot_package_goreleaser_patch_71f6bd2489d0fa6fd567dc692d96da8b681082b8_65c60fb01e2d171458d3cfda_24_02_09_11_42_41) are successful and use the latest goreleaser release:

### CODE REVIEW

**Comment by jeroenvervaeke** [comment]
Does this still work?

Looks like `archives.rlcp` is deprecated: https://goreleaser.com/deprecations/#archivesrlcp_1

**Comment by andreaangiolillo** [comment]
@jeroenvervaeke it is a default behavior change.

> This is not so much a deprecation property (yet), as it is a default behavior change.

**Comment by jeroenvervaeke** [comment]
> @jeroenvervaeke it is a default behavior change. Am I missing something? 🤔 Now the default behaviour is that the prop is set to true whereas before was set to false.
> 
> > This is not so much a deprecation property (yet), as it is a default behavior change.

Oh my bad, I interpreted it in a different way

**Review by jeroenvervaeke — APPROVED** [review]
LGTM

**Pull request merged**
