### PR TITLE
CLOUDP-238529: CLI supports AKO 2.3.0 resources

### PR DESCRIPTION
**Pull request by helderjs**
## Proposed changes

This PR only enables support for the recently released AKO 2.3 and its features

_Jira ticket:_ CLOUDP-238529

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by josvazg — COMMENTED** [review]
LGTM, waiting on CI

**Review by igor-karpukhin — APPROVED** [review]
LGTM 👍

**Comment by josvazg** [comment]
Also related to CLOUDP-239409

**Review by jwilliams-mongo — APPROVED** [review]

**Comment by josvazg** [comment]
I will need to work on this for 2.3.1 soon, is this only waiting on an extra review?

**Review by gssbzn — APPROVED** [review]

**Pull request merged**
