### PR TITLE
CLOUDP-118459: [cli] quickstart should verify authentication the same as other commands

### PR DESCRIPTION
**Pull request by gssbzn**
## Proposed changes

_Jira ticket:_ CLOUDP-118459

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongocli/blob/master/CONTRIBUTING.md) (if appropriate)
- [x] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [x] I have updated [e2e/E2E-TESTS.md](https://github.com/mongodb/mongocli/blob/master/e2e/E2E-TESTS.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

```bash
./bin/atlas quickstart -P asdasdasd
Error: this action requires authentication

To log in using your Atlas username and password, run: atlas auth login
To set credentials using API keys, run: atlas config init
```

### CODE REVIEW

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Review by blva — APPROVED** [review]
LGTM, could you please share what's the new output when the credentials and tokens are not set?

**Comment by gssbzn** [comment]
>LGTM, could you please share what's the new output when the credentials and tokens are not set?

Updated the description with it

**Review by colm-quinn — APPROVED** [review]
LGTM (also thanks for the output, that really helped me check the impact/validate an assumption)

**Pull request merged**
