### PR TITLE
CLOUDP-229525: allow all api calls for gov

### PR DESCRIPTION
**Pull request by tibulca**
## Proposed changes

_Jira ticket:_ CLOUDP-#

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by blva — DISMISSED** [review]
LGTM if LGTEV

**Comment by jeroenvervaeke** [comment]
Should the 2 calls in [telemetry.go](https://github.com/mongodb/mongodb-atlas-cli/blob/08f047cab21cc15fdb9b48c02b2c99101ed79130/internal/store/atlas/serverless_instances.go) be covered?

**Comment by gssbzn** [comment]
>Should the 2 calls in telemetry.go be covered?

Those are actually the only ones we may never enable

**Review by jeroenvervaeke — APPROVED** [review]
LGTM

**Review by gssbzn — APPROVED** [review]

**Review by jeroenvervaeke — APPROVED** [review]
LGTM

**Comment by tibulca** [comment]
evergreen refresh

**Pull request merged**
