### PR TITLE
task: update sdk to latest stable

### PR DESCRIPTION
**Pull request by gssbzn**
Update to the  latest version of the SDK

### CODE REVIEW

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Review by tibulca — APPROVED** [review]

**Review by colm-quinn — APPROVED** [review]
LGTM

**Review by wtrocki — APPROVED** [review]
Out of curiosity: Did you run make script or do you do that manually?

https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md#update-automation

**Comment by gssbzn** [comment]
>Did you run make script or do you do that manually?

manually, I saw the script too late :(

**Pull request merged**
