### PR TITLE
CLOUDP-210683: fix: add 2.0.0 major version of AKO

### PR DESCRIPTION
**Pull request by s-urbaniak**
## Proposed changes

_Jira ticket:_ CLOUDP-210683

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by s-urbaniak** [comment]
cc @igor-karpukhin

**Comment by s-urbaniak** [comment]
cc @gssbzn

**Review by gssbzn — APPROVED** [review]
LGTM if LGTEVG

**Comment by s-urbaniak** [comment]
ok, we have proper vendoring in place finally, now continuing here.

**Comment by s-urbaniak** [comment]
closing in favor of #2459

**Pull request closed without merging**
