### PR TITLE
DOCSP-19019 Correct info in mongocli ops-manager alerts settings docu…

### PR DESCRIPTION
**Pull request by pierwill**
…mentation

## Proposed changes

_Jira ticket:_  https://jira.mongodb.org/browse/DOCSP-19019

Closes #[issue number]

## Checklist

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by pierwill** [comment]
bump

**Review by sarahsimpers — DISMISSED** [review]
Copy LGTM but I would ping the developer team's slack to have them stamp with a tech review to make sure this is technically accurate. Thanks!

**Review by gssbzn — CHANGES_REQUESTED** [review]
the txt files are auto generated, please update the commands

**Comment by gssbzn** [comment]
please also merge in master

**Comment by pierwill** [comment]
@gssbzn Is marking these are required done by adding `Args:  require.ExactArgs(1)`? (as in https://github.com/pierwill/mongodb-atlas-cli/blob/ef48c2696423da51ff5d8081458f5cba213df0fb/internal/cli/atlas/alerts/settings/delete.go#L59)

**Comment by gssbzn** [comment]
`Args:  require.ExactArgs(1)`  is for arguments for flags you need to mark the flag as required via `cmd.MarkFlagRequired("flagName"` like https://github.com/mongodb/mongodb-atlas-cli/blob/4f4e74526d10dee43421da7007b4d2f69180739f/internal/cli/atlas/teams/users/delete.go#L84

**Comment by pierwill** [comment]
@gssbzn Or is it part of `cobra.Command.Annotations`?

**Review by gssbzn — APPROVED** [review]
LGTM thanks

**Pull request merged**
