### PR TITLE
patch: hide watcher flags for atlas clusters delete

### PR DESCRIPTION
**Pull request by matt-condon**
## Proposed changes

Temporarily hide watcher flag for atlas clusters delete in preparation for patch release 

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by blva — APPROVED** [review]
LGTM. (double-checking - this functionality was going to be added in the next release right?)

**Comment by matt-condon** [comment]
> LGTM. (double-checking - this functionality was going to be added in the next release right?)

Yep! That's the plan
I'll revert post-release

**Review by andmatei — APPROVED** [review]
LGTM

**Review by sarahsimpers — APPROVED** [review]
LGTM

**Review by swattyT — APPROVED** [review]

**Pull request merged**
