### PR TITLE
CLOUDP-167779: Migrate private endpoints services

### PR DESCRIPTION
**Pull request by andmatei**
## Proposed changes
Migrate the remaining private endpoints commands after SDK fixes.

_Jira ticket:_ CLOUDP-167779

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [test/README.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/test/README.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by wtrocki — APPROVED** [review]
Reviewed locally. LGTM

**Review by wtrocki — APPROVED** [review]
Reviewed locally. LGTM after kubernetes tests:

https://spruce.mongodb.com/task/mongodb_atlas_cli_master_e2e_atlas_kubernetes_atlas_kubernetes_e2e_patch_12114345f0a75f4116d79240748758e358e02fc9_6467923161837d083e336b59_23_05_19_15_13_54/logs?execution=0

**Review by swattyT — APPROVED** [review]
LGTM!

**Comment by andmatei** [comment]
kubernetes tests pass. merging <3

**Pull request merged**
