### PR TITLE
CLOUDP-121000: [Atlas CLI] Telemetry - Remove Feature Flag

### PR DESCRIPTION
**Pull request by johansteyn**
## Proposed changes

_Jira ticket:_ CLOUDP-121000

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [e2e/E2E-TESTS.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/e2e/E2E-TESTS.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by colm-quinn — APPROVED** [review]
LGTM!

**Review by fmenezes — APPROVED** [review]
ship it!

**Comment by johansteyn** [comment]
evergreen retry

**Comment by blva** [comment]
Looking into the failures!

**Review by blva — APPROVED** [review]

**Pull request merged**
