### PR TITLE
DOCSP-22236: Updates atlas backups restores documentation

### PR DESCRIPTION
**Pull request by sarahsimpers**
## Proposed changes

Adds details on which options are required for automated restores only

[Jira ticket](https://jira.mongodb.org/browse/DOCSP-22236)

## Checklist

- [ X ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/CONTRIBUTING.md) (if appropriate)
- [ ] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [ ] I have updated [e2e/E2E-TESTS.md](https://github.com/mongodb/mongodb-atlas-cli/blob/master/e2e/E2E-TESTS.md) (if an e2e test has been added)
- [ ] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by blva — DISMISSED** [review]
LGTM!

**Review by jwilliams-mongo — APPROVED** [review]
@sarahsimpers LGTM

**Comment by andreaangiolillo** [comment]
@sarahsimpers doc test is failing. Did you run `make gen-docs` ?

**Review by jwilliams-mongo — APPROVED** [review]
@sarahsimpers LGTM

**Pull request merged**
