### PR TITLE
CLOUDP-171151: Atlas-SDK-go Update

### PR DESCRIPTION
**Pull request by wtrocki**
This PR makes a lot of regexp renames in order to integrate with the new SDK. 
Additionally we fix compilation issues related to the fact that we had a lot of breaking changes.

## Things to consider

1. int32 introduced in previous migrations were reverted
2. Usages of float32 for the dates were reverted to the integers (as they were correctly mapped in the OpenAPI).

Apart from that all other changes are just import statements

### CODE REVIEW

**Review by blva — APPROVED** [review]
lgtm

**Comment by wtrocki** [comment]
@swattyT I will be rebasing all outstanding PRs to include the new released version of the SDK.
This is using **official SDK version**. We can easily move to the dev version if needed.

**Review by fmenezes — DISMISSED** [review]
code LGTM, make sure evergreen is happy

**Comment by wtrocki** [comment]
Integration tests passed apart from Kubernetes (which is broken on master)

**Review by fmenezes — APPROVED** [review]

**Pull request merged**
